#!/usr/bin/env bash
# Quick Reference Guide for Token Helper Development

echo "═══════════════════════════════════════════════════════════"
echo "  Token Helper - Development Quick Reference"
echo "═══════════════════════════════════════════════════════════"
echo ""

echo "📁 Project Structure:"
echo "  ├── main.py               → Application entry point"
echo "  ├── build.ps1             → Build executable script"
echo "  ├── README.md             → Documentation"
echo "  ├── requirements.txt      → Python dependencies"
echo "  ├── VERSION               → Current version (v1.0.0)"
echo "  ├── CONTRIBUTING.md       → How to contribute"
echo "  ├── CODE_OF_CONDUCT.md    → Community guidelines"
echo "  ├── SECURITY.md           → Security policy"
echo "  ├── scripts/"
echo "  │   └── version.py        → Versioning helper"
echo "  ├── ui/"
echo "  │   └── index.html        → Web UI"
echo "  └── .github/"
echo "      ├── workflows/        → GitHub Actions CI/CD"
echo "      └── ISSUE_TEMPLATE/   → Issue templates"
echo ""

echo "🚀 Getting Started:"
echo "  python -m venv .venv"
echo "  .\\\.venv\\\\Scripts\\\\Activate.ps1  (Windows)"
echo "  pip install -r requirements.txt"
echo "  python main.py"
echo ""

echo "📦 Building Executable:"
echo "  .\\build.ps1"
echo "  → Output: ./dist/BoostCypher Token Helper.exe"
echo ""

echo "🔧 Versioning:"
echo "  python scripts/version.py              # Show version"
echo "  python scripts/version.py patch \"msg\"  # v1.0.0 → v1.0.1"
echo "  python scripts/version.py minor \"msg\"  # v1.0.0 → v1.1.0"
echo "  python scripts/version.py major \"msg\"  # v1.0.0 → v2.0.0"
echo ""

echo "🔄 Release Workflow:"
echo "  1. Make changes on main/src branch"
echo "  2. Test thoroughly"
echo "  3. Run: python scripts/version.py minor \"Description\""
echo "  4. GitHub Actions builds & uploads executable"
echo "  5. Release created at: https://github.com/chilhoekdev/token-helper/releases"
echo ""

echo "📋 Issue Templates:"
echo "  🐛 Bug Report      → GitHub → Issues → New Issue → Bug Report"
echo "  ✨ Feature Request → GitHub → Issues → New Issue → Feature Request"
echo "  📚 Documentation   → GitHub → Issues → New Issue → Documentation"
echo "  🔧 Config Issue    → GitHub → Issues → New Issue → Config Issue"
echo ""

echo "📊 GitHub Actions Workflows:"
echo "  ✓ build-and-release.yml → Builds EXE on tags/commits"
echo "  ✓ code-quality.yml      → Linting & formatting checks"
echo ""

echo "🐛 Reporting Issues:"
echo "  Always use GitHub issue templates for bug reports"
echo "  Include: description, steps to reproduce, expected behavior, OS info"
echo ""

echo "🤝 Contributing:"
echo "  1. Fork the repository"
echo "  2. Create feature branch: git checkout -b feature/your-feature"
echo "  3. Make changes and test"
echo "  4. Commit: git commit -m \"Clear description\""
echo "  5. Push and create Pull Request"
echo "  → Use pull request template when creating PR"
echo ""

echo "📝 Important Files:"
echo "  • README.md         → Main documentation"
echo "  • CONTRIBUTING.md   → Contribution guidelines"
echo "  • CODE_OF_CONDUCT.md → Community standards"
echo "  • SECURITY.md       → Security vulnerability reporting"
echo "  • .gitignore        → Files excluded from git"
echo ""

echo "🔐 Security:"
echo "  • Never commit secrets or tokens"
echo "  • Check .gitignore for sensitive file patterns"
echo "  • Report security issues privately (see SECURITY.md)"
echo ""

echo "📞 Resources:"
echo "  • GitHub Issues:      https://github.com/chilhoekdev/token-helper/issues"
echo "  • Discussions:        https://github.com/chilhoekdev/token-helper/discussions"
echo "  • Releases:           https://github.com/chilhoekdev/token-helper/releases"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "  For detailed info, see README.md and CONTRIBUTING.md"
echo "═══════════════════════════════════════════════════════════"
